name: story_app_initial
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  provider: ^6.1.2
  http: ^1.3.0
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.1
  flutter_speed_dial: ^7.0.0
  image_picker: ^1.1.2
  image: ^4.5.3
  mime: ^2.0.0
  path: ^1.9.1
  http_parser: ^4.1.2
  flutter_image_compress: ^2.4.0
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/block.gif